enum ActionTypeKeys {
  //
  // User Actions
  //

  USER_LOGGED_IN = 'USER_LOGGED_IN',

  //
  // Node Actions
  //

  PUBLIC_PERSON_LIST_UPDATED = 'PUBLIC_PERSON_LIST_UPDATED',
  PUBLIC_PLACE_LIST_UPDATED = 'PUBLIC_PLACE_LIST_UPDATED',
  PRIVATE_PERSON_LIST_UPDATED = 'PRIVATE_PERSON_LIST_UPDATED',
  PRIVATE_PLACE_LIST_UPDATED = 'PRIVATE_PLACE_LIST_UPDATED',

  //
  // Group Actions
  //

  GROUP_LIST_UPDATED = 'GROUP_LIST_UPDATED',

  //
  // Map Actions
  //

  USER_POSITIION_CHANGED = 'USER_POSITIION_CHANGED',

}

export default ActionTypeKeys;