platform :ios, '11.0'

target 'Smartshare' do
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS
pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Fabric'
pod 'Crashlytics'
pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  # Add any other subspecs you want to use in your project
]
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'
  
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'



  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
