enum ActionTypeKeys {
  //
  // Node Actions
  //

  PUBLIC_PERSON_LIST_UPDATED = 'PUBLIC_PERSON_LIST_UPDATED',
  PUBLIC_PLACE_LIST_UPDATED = 'PUBLIC_PLACE_LIST_UPDATED',
  PRIVATE_PERSON_LIST_UPDATED = 'PRIVATE_PERSON_LIST_UPDATED',
  PRIVATE_PLACE_LIST_UPDATED = 'PRIVATE_PLACE_LIST_UPDATED',
  TRACKED_NODE_LIST_UPDATED = 'TRACKED_NODE_LIST_UPDATED',

  //
  // Friend Actions
  //

  FRIEND_LIST_UPDATED = 'FRIEND_LIST_UPDATED',
  RELATION_LIST_UPDATED = 'RELATION_LIST_UPDATED',

  //
  // Map Actions
  //

  USER_POSITIION_CHANGED = 'USER_POSITIION_CHANGED',

  //
  // Notification Actions
  //

  NOTIFICATION_LIST_UPDATED = 'NOTIFICATION_LIST_UPDATED',

}

export default ActionTypeKeys;