#!/usr/bin/python

import subprocess
import sys

def build_package(name):
    handler = ''
    
    if name in ['create_node', 'post_node', 'get_nodes', 'get_all_nodes', 'send_text', 'update_group', \
     'get_public_nodes', 'create_group', 'join_group', 'get_groups', 'add_friend', 'get_invites']:
        handler = name + '.py'
        command = 'cp ./deployment_packages/template.zip ./deployment_packages/' + name + '.zip'
        rc = subprocess.call(command, shell=True)
        if rc != 0:
            return
        
        command = 'zip -gj ./deployment_packages/' + name + '.zip' + ' ' + handler 
        rc = subprocess.call(command, shell=True)
        if rc != 0:
            return 
        


if __name__ == '__main__':build_package(sys.argv[1])
